version: "3.8"
services:
  neo4j:
    image: neo4j:4.4.20-community
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    ports:
      - 8080:8080
